### ISSUE TITLE
Some Icon Requests are show in the Log

### ISSUE THREAD

**Issue by vvbasti** [sanjoyg/dirigera_platform#104]
Some icons missing in Stock Icons

Unknown icon scenes_clean_sparkles
Unknown icon scenes_briefcase
Unknown icon scenes_brightness_up
Unknown icon scenes_disco_ball
Unknown icon scenes_leave_home

Wich Plugin or HACS contains this Icons ? or it´s custome ?

**Comment by sanjoyg** [comment]
Fixed in beta release, please check

**Comment by vvbasti** [comment]
Hy, you are very fast.
I think is solved, i cant see any icon error messages. perfect
