### ISSUE TITLE
Remote support not working

### ISSUE THREAD

**Issue by JanuszSmola** [sanjoyg/dirigera_platform#16]
I see in the description that "STYRBAR Remotes" should be working but I can't find it anywhere in the HA. After I enter IP address and press action button I only see the bulbs on the list and I don't see a remote. I make sure that the remote I own is STYRBAR (the square one with 2 arrow buttons and 2 dim/light buttons).

Here is what I see in HA:
<img width="617" alt="Screenshot 2024-03-11 at 23 24 08" src="https://github.com/sanjoyg/dirigera_platform/assets/26741985/218b5449-1fd9-43bb-adce-c0a4e16de89a">

I'm pretty new to HA so I'm not really sure where should I be able to see the remote but I can't find it anywhere. I run HA in docker container and I don't see any logs connected to remotes. Any tips how to get this working?

**Comment by sanjoyg** [comment]
can you post the JSON from the log, read the readme how to do it. that would help

**Comment by sanjoyg** [comment]
Can you please run the service command and post the JSON that would apply
in the log

**Comment by slajob** [comment]
Hi, I found the same error in my setup. @JanuszSmola probably you have new SOMRIG shortcut button 
![image](https://github.com/sanjoyg/dirigera_platform/assets/33373409/856f1d88-8861-44c2-84d7-f2b724af215d)
That's right? 
I thing there is a bug in dirigera lib and I'll try to fix it in Leggin repository

**Comment by slajob** [comment]
Update:
Bug found and fixed in https://github.com/Leggin/dirigera/pull/53
So after merge we can update dirigera lib version 😇

**Comment by sanjoyg** [comment]
@slajob is it merged... once merged will you updated the requirements.txt and cut a new release

**Comment by slajob** [comment]
Sure , When I got accepted my PR in dirigera repo I will do it 😁

**Comment by sanjoyg** [comment]
@slajob is the PR submitted... if not then can put a fix in the patch class

**Comment by sanjoyg** [comment]
@slajob updated the requirements.txt and pushed a new release

@JanuszSmola please try with release 1.3.4
