### ISSUE TITLE
Failing to add mock devices

### ISSUE THREAD

**Issue by acces90** [sanjoyg/dirigera_platform#2]
I am failing to make the mock devices work.

I get the following log entry for the devices:

> Logger: homeassistant.setup
Source: setup.py:403
First occurred: 21:43:27 (20 occurrences)
Last logged: 22:35:57

>Unable to prepare setup for platform 'dirigera_platform.light': Platform not found (cannot import name 'Attributes' from 'dirigera.devices.device' (/usr/local/lib/python3.11/site-packages/dirigera/devices/device.py)).
Unable to prepare setup for platform 'dirigera_platform.switch': Platform not found (cannot import name 'Attributes' from 'dirigera.devices.device' (/usr/local/lib/python3.11/site-packages/dirigera/devices/device.py)).
Unable to prepare setup for platform 'dirigera_platform.binary_sensor': Platform not found (cannot import name 'Attributes' from 'dirigera.devices.device' (/usr/local/lib/python3.11/site-packages/dirigera/devices/device.py)).
Unable to prepare setup for platform 'dirigera_platform.sensor': Platform not found (cannot import name 'Attributes' from 'dirigera.devices.device' (/usr/local/lib/python3.11/site-packages/dirigera/devices/device.py)).
Unable to prepare setup for platform 'dirigera_platform.cover': Platform not found (cannot import name 'Attributes' from 'dirigera.devices.device' (/usr/local/lib/python3.11/site-packages/dirigera/devices/device.py)).

**Comment by sanjoyg** [comment]
Is there a way you can get to HASS Terminal and check the version of the dirigera package. Looks like either its the wrong package or  isnt installed correctly.

**Comment by acces90** [comment]
I was on an older branch version, which i tried with pyscript, and it did not update it manually.. although your requirements file says it needed a newer one... well manually uninstalling and installing the newest dirigera package helped. but it was a mess doing so, since I had to do this through pyscript... is there another way to see what packages are currently installed? When i checked pip on the hassio cli it said there wasn't any packages installed at all..

**Comment by sanjoyg** [comment]
I wouldnt know, but HASS would run all integration in a container so you wouldnt see the packages
