### ISSUE TITLE
Duplicate SOMRIG devices created during import

### ISSUE THREAD

**Issue by bjorncs** [sanjoyg/dirigera_platform#24]
I have 3 SOMRIG button devices in my smart home setup. During the inital setup I've ended up with 6 devices in total in HA. The duplicates are all named `IKEA Dirigera Hub : 10.0.0.3` and do not have any entities.

<img width="1454" alt="Screenshot 2024-03-29 at 19 36 49" src="https://github.com/sanjoyg/dirigera_platform/assets/798335/9115c646-f032-4e17-b81a-8c20bef85709">

[dirigera-devices.json](https://github.com/sanjoyg/dirigera_platform/files/14807739/dirigera-devices.json)

**Comment by sanjoyg** [comment]
Can you check with the latest release again.

**Comment by bjorncs** [comment]
Duplicates still there with 1.3.5.1. I removed the devices and re-paired with Dirigera. The duplicates reappeared once again.

**Comment by sanjoyg** [comment]
I got some time to look at the JSON. The hub returns two devices with different id but same serial number.
For example the first SOMRIG with name EntranceButton has two entries with almost same id except _1 and _2 at end. Same serial number but different attribute "switchLabel".

In one case the attribute value is "Shortcut 1" and other has "Shortcut 2"

Can you tell me how this is related to the physical device as I dont have one

**Comment by bjorncs** [comment]
The SOMRIG remote control consist of two buttons, each button supports single/double/long click as separate triggers.

After investigating the scene configuration dump I created fromthe https://github.com/Leggin/dirigera library it's clear that the two "devices" actually represents the two buttons of a single remote. The devices having suffix `_1` represents the top button (the one with a single dot imprinted), while `_2` represents the lower button. 

The latter always has an empty `customName` and missing the attributes `batteryPercentage` and  `room`. Otherwise identical.

**Comment by sanjoyg** [comment]
Closing this Issue, we shall track with the issue #29

**Comment by bjorncs** [comment]
Not sure how this relates to #29. I'll working a on contribution that will remove the duplicate devices.

**Comment by sanjoyg** [comment]
My bad, will get to fix this once we fix the empty scene creation that @slajob  is working on.

**Comment by bjorncs** [comment]
I drafted https://github.com/sanjoyg/dirigera_platform/pull/33. @slajob will hopefully be able to reuse most of the additional code introduced in his solution.
