### ISSUE TITLE
Vallhorn motion sensor always reported as "clear"

### ISSUE THREAD

**Issue by Enchufa2** [sanjoyg/dirigera_platform#26]
Thanks for this integration. I installed this to incorporate a Vallhorn motion sensor to some automations, but unfortunately it's always reported as "clear" when e.g. the Google Home app correctly reports the activity.

I've dumped the JSON with and without motion being detected and I noticed that this sensor does **not** use the `isOn` attribute, but the `isDetected` one instead. Here's the dump while I'm standing in front of the sensor:

```json
{
   "id":[redacted],
   "relationId":[redacted],
   "type":"sensor",
   "deviceType":"motionSensor",
   "createdAt":"2024-03-29T02:18:45.000Z",
   "isReachable":true,
   "lastSeen":"2024-03-30T12:13:56.000Z",
   "attributes":{
      "customName":[redacted],
      "firmwareVersion":"1.0.64",
      "hardwareVersion":"1",
      "manufacturer":"IKEA of Sweden",
      "model":"VALLHORN Wireless Motion Sensor",
      "productCode":"E2134",
      "serialNumber":[redacted],
      "batteryPercentage":87,
      "isOn":false,
      "isDetected":true,
      "motionDetectedDelay":20,
      "identifyPeriod":0,
      "identifyStarted":"2000-01-01T00:00:00.000Z",
      "permittingJoin":false,
      "sensorConfig":{
         "scheduleOn":false,
         "onDuration":600,
         "schedule":{
            "onCondition":{
               "time":"22:00"
            },
            "offCondition":{
               "time":"06:00"
            }
         }
      },
      "circadianPresets":[
         
      ]
   },
   "capabilities":{
      "canSend":[
         
      ],
      "canReceive":[
         "customName"
      ]
   },
   "room":{
      [redacted]
   },
   "deviceSet":[
      
   ],
   "remoteLinks":[
      
   ],
   "isHidden":false
}
```

Note the `isDetected` attribute set to true, which is false when the view is clear. Is there a quick way to patch my installation to use this attribute while a proper fix is implemented?

**Comment by Enchufa2** [comment]
Answering my question, yes, there's a quick workaround. For reference:

- I've added `is_detected: bool` here: https://github.com/sanjoyg/dirigera_platform/blob/3f3727a8d450363bea80f7460d1b11483263247d/custom_components/dirigera_platform/dirigera_lib_patch.py#L21-L23
- I've changed this line to read the `is_detected` attribute instead: https://github.com/sanjoyg/dirigera_platform/blob/3f3727a8d450363bea80f7460d1b11483263247d/custom_components/dirigera_platform/binary_sensor.py#L104-L106

And now it works perfectly. This works for me because I'm planning to use Vallhorn sensors only, but a proper fix probably is bit more involved.

**Comment by sanjoyg** [comment]
Just to clarify, so the value to read is is_on and not is_detected is that correct?

**Comment by sanjoyg** [comment]
Try release 1.3.5.1 and let know. The issue should be fixed

**Comment by Enchufa2** [comment]
I confirm it works perfectly, thanks!

**Comment by sanjoyg** [comment]
Great, closing the issues
