### ISSUE TITLE
Trigger scenes 

### ISSUE THREAD

**Issue by bjorncs** [sanjoyg/dirigera_platform#27]
The HA integration for Philips Hue can trigger Hue defined scenes through a [service call](https://www.home-assistant.io/integrations/hue/#scenes). Having the same functionality for Dirigera is conventient for smart home setups where most or all lighting is managed by the Ikea ecosystem. The functionality for triggering scenes is already available through the underlying [Dirigera integration](https://github.com/Leggin/dirigera?tab=readme-ov-file#scene).

**Comment by bjorncs** [comment]
@sanjoyg Let me know if you're interested in a contribution.

**Comment by sanjoyg** [comment]
@bjorncs  would love for you to contribute to this, @slajob  is already working on it. Would you collaborate with him please. The thought process is that an empty scene would be created linking the remote which would allow for the events to flow in

**Comment by bjorncs** [comment]
My proposal is in https://github.com/sanjoyg/dirigera_platform/pull/39. I had a chat with @slajob in Discord and he's aware about this contribution.

**Comment by sanjoyg** [comment]
Cool which discord channel… would love to join in

**Comment by slajob** [comment]
@sanjoyg just on dm. Add me and we will create a server 😃 Slawke#4429

**Comment by sanjoyg** [comment]
I am a green on discord, so would need directions ...sorry :-(

**Comment by slajob** [comment]
In desktop app, click on your profile, and then green # button and send your username :P
