### ISSUE TITLE
Name of reposetory ?

### ISSUE THREAD

**Issue by anders-ash** [sanjoyg/dirigera_platform#50]
Installing
    • Like all add-on installation goto the "HACS" option in the left menu bar in home assistant 
    • Select Integration and add custom repository and enter this repositoy 
What is the correct name of repository?

I have tried different name with no sucess.

I have tried

[dirigera_platform ](https://github.com/sanjoyg/dirigera_platform)
IKEA Dirigera Hub Integration

Anders Hansen

**Comment by anders-ash** [comment]
Thankyou forI have missed the tre dots.It works fine nowAnders HansenDen 21. maj 2024 kl. 14.44 skrev Sanjoy Ghosh ***@***.***>:﻿
got to HACS -> Integrations > click the three dots menu from top right hand side -> custom repository
brings up a popup. In the repository paste the following : "https://github.com/sanjoyg/dirigera_platform"
In category choose "Integration"
Once u add this the integration will be added

**Comment by sanjoyg** [comment]
did it work? If it did do close the issue. thank you

**Comment by anders-ash** [comment]
Thanks for your help. It works fine.
