### ISSUE TITLE
Doorsensor event propagation no longer instant

### ISSUE THREAD

**Issue by Sikerdebaard** [sanjoyg/dirigera_platform#53]
Hi,

A few days ago, PR #49 was merged, which fixed the event propagation for the door sensors, ensuring they updated instantly.

However, in the current version, this is no longer the case. Some recent code changes have caused the event propagation to revert to the previous mode, updating once every 30 seconds.

I had to downgrade back to version 1.7.4 to restore instant event propagation.

**Comment by sanjoyg** [comment]
would u please enable debug  and paste the log lines during the door sensor update will help fix the code

**Comment by sanjoyg** [comment]
Good catch, should be fixed now. Try the new release and let know

**Comment by Sikerdebaard** [comment]
It works! Thanks for solving this. 👍
