### ISSUE TITLE
Error while setting up dirigera_platform platform for binary_sensor

### ISSUE THREAD

**Issue by snope** [sanjoyg/dirigera_platform#58]
Hey there,

First of all, many thanks for this amazing module. It works like a charm for my power plugs and air filters. 

Recently, I added a bunch of PARASOLL window/door sensors and ran into the following issue:

> Logger: homeassistant.components.binary_sensor
> Source: helpers/entity_platform.py:364
> integration: Binary sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues]>(https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
> First occurred: July 14, 2024 at 4:51:07 PM (6 occurrences)
> Last logged: 2:00:23 PM

> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
>     await asyncio.shield(awaitable)
>   File "/config/custom_components/dirigera_platform/binary_sensor.py", line 58, in async_setup_entry
>     hub_open_close_sensors : list[OpenCloseSensor] = **await hass.async_add_executor_job(hub.get_open_close_sensors)**
> 
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = **self.fn(self.args, self.kwargs)**
> 
>   File "/usr/local/lib/python3.12/site-packages/dirigera/hub/hub.py", line 270, in get_open_close_sensors
>     return **[dict_to_open_close_sensor(sensor, self) for sensor in sensors]**
> 
>   File "/usr/local/lib/python3.12/site-packages/dirigera/devices/open_close_sensor.py", line 31, in dict_to_open_close_sensor
>     return **OpenCloseSensor(dirigeraClient=dirigera_client, **data)**
>      
>   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
> pydantic.error_wrappers.ValidationError: 1 validation error for OpenCloseSensor
> attributes -> isOpen
>   field required (type=value_error.missing)

At first, it seemed to work. I added four sensors, and they showed up, but later, while adding another ten, the issues occurred. I reconnected multiple times, removed the configuration and added it again, but all window/door sensors are now excluded, and I only see the error above every time I reconnect HA and the dirigera hub. 

Any idea? Anything I can provide in addition for debugging the issue? 

Many thanks,
David

**Comment by sanjoyg** [comment]
Will you provide the json dump please. Instructions are available in the
readme

**Comment by snope** [comment]
Okay, as usual, the issue was in front of the screen. Calling the _dirigera_platform.dump_data_ service wasn't producing any JSON in the logs. I decided then to remove everything, reboot (instead of reload), and re-install everything, and suddenly, it worked. 

Thanks, and sorry to bother you in the first place.
