### ISSUE TITLE
New Version of HomeAssitant

### ISSUE THREAD

**Issue by techker** [sanjoyg/dirigera_platform#59]
Hey, Thx for the Addon! 
The new version of HomeAssitant steps are different,and once you get it installed the screen only shows

Add to dashboard -> but default and map do says No views in this dashboard.

i click Update then dialog shows but only get addon details, there is no place to configure the bridge to start adding the ip..

do we need to edit some file?

Core: 2024.7.3
Sup :2024.06.2
OP:12.4
FrontEnd:20240710.0

**Comment by doomedraven** [comment]
i just installed it on my side, and it worked just fine

**Comment by techker** [comment]
what steps did you take? maybe the doc is missing something..or my
A.D.D..lol

all i see is the card update..

but dont see the devices attached to it

**Comment by sanjoyg** [comment]
Will you follow the documentation to generate the json

**Comment by doomedraven** [comment]
@techker after install from HACS
So yes initially it was a bit confusing, bcz im new to this plugin. But i got it working by going to
1. http://homeassistant.local:8123/config/integrations/dashboard
2. Press add integration and search for `Ikea Dirigera`


* <img width="434" alt="Captura de pantalla 2024-07-31 a las 7 30 06" src="https://github.com/user-attachments/assets/9947e98a-f332-42c0-9fa7-fbe225c0e1b3">
* Double click it
* <img width="348" alt="Captura de pantalla 2024-07-31 a las 7 30 33" src="https://github.com/user-attachments/assets/e9c4ef22-30b9-4b38-929b-d8fa80f6b7c8">

**Comment by techker** [comment]
that worked!thx

**Comment by doomedraven** [comment]
@sanjoyg i guess you can close this issue
