### ISSUE TITLE
Battery percentage for non IKEA sensors.

### ISSUE THREAD

**Issue by dreamfalcon** [sanjoyg/dirigera_platform#62]
Would be possible to add battery percentage for non IKEA sensors?
{
      "id":"xxx",
      "type":"sensor",
      "deviceType":"environmentSensor",
      "createdAt":"2024-08-05T13:24:30.000Z",
      "isReachable":true,
      "lastSeen":"2024-08-06T09:08:49.000Z",
      "attributes":{
         "customName":"Sensor rua",
         "model":"SNZB-02P",
         "manufacturer":"eWeLink",
         "firmwareVersion":"2.1.0",
         "hardwareVersion":"0",
         "serialNumber":"A",
         "batteryPercentage":100,
         "currentTemperature":22.7,
         "currentRH":75,
         "permittingJoin":false,
         "otaStatus":"upToDate",
         "otaState":"readyToCheck",
         "otaProgress":0,
         "otaPolicy":"autoUpdate",
         "otaScheduleStart":"00:00",
         "otaScheduleEnd":"00:00"
      },
      "capabilities":{
         "canSend":[
            
         ],
         "canReceive":[
            "customName"
         ]
      }
   },

**Comment by sanjoyg** [comment]
I could, but SonOff devices have a great add-on. Or is this linked to the IKEA dirigera hub?

**Comment by dreamfalcon** [comment]
> I could, but SonOff devices have a great add-on. Or is this linked to the IKEA dirigera hub?

Its linked to the IKEA hub.
I have a tuya hub with Matter but dosent play well wit the sensor. The dirigera hub seems to be much better with the mesh part.

**Comment by sanjoyg** [comment]
The JSON doesnt include deviceSet and remoteLinks mandatory json elements. Does this even appear in the device list?

**Comment by dreamfalcon** [comment]
> The JSON doesnt include deviceSet and remoteLinks mandatory json elements. Does this even appear in the device list?

<img width="506" alt="image" src="https://github.com/user-attachments/assets/e7f85b5a-191a-479a-aa89-ece34e25f57a">
<img width="374" alt="image" src="https://github.com/user-attachments/assets/a9bd4598-826c-424c-8324-9db36f548281">

**Comment by dreamfalcon** [comment]
Matter support was just added for more devices and they included the battery state for this sensors.
