### ISSUE TITLE
Power Doesn't Update

### ISSUE THREAD

**Issue by dmckillican** [sanjoyg/dirigera_platform#65]
I’ve successfully added the platform and linked it to my Home Assistant. While the system is generally functioning, I’m facing an issue where I can’t turn lights on after turning them off. Additionally, I’ve noticed that the power status doesn’t update. However, I can turn the lights back on by using the dimmer function. I’ve also noticed a bunch of system logs that provide some insights into the problem.

Any suggestions? Thanks in advance :)

**First log:**
This error originated from a custom integration.

Logger: custom_components.dirigera_platform
Source: custom_components/dirigera_platform/hub_event_listener.py:154
integration: IKEA Dirigera Hub Integration (documentation, issues)
First occurred: 5:02:37 PM (251 occurrences)
Last logged: 5:58:08 PM

error processing hub event

**Second log:**
This error originated from a custom integration.

Logger: custom_components.dirigera_platform
Source: custom_components/dirigera_platform/hub_event_listener.py:155
integration: IKEA Dirigera Hub Integration (documentation, issues)
First occurred: 5:02:37 PM (251 occurrences)
Last logged: 5:58:08 PM

{"id":"b1716ed3-d1bc-49a2-ba69-3e3f7ab1d2d0","time":"2024-08-23T07:58:07.000Z","specversion":"3.160.0","source":"urn:com:ikea:homesmart:iotc:zigbee","type":"deviceStateChanged","data":{"id":"0dcf49bb-1dd1-4377-97af-b8d40fab688b_1","type":"light","deviceType":"light","createdAt":"2022-12-19T07:16:01.000Z","isReachable":true,"lastSeen":"2024-08-23T07:58:07.000Z","attributes":{"isOn":true},"remoteLinks":["9371c9ac-3933-48fc-9bc5-adee7f1ac6ac_1"]}}
{"id":"d94b79e5-8dba-4313-a092-755ac68cc467","time":"2024-08-23T07:58:07.000Z","specversion":"3.160.0","source":"urn:com:ikea:homesmart:iotc:zigbee","type":"deviceStateChanged","data":{"id":"f58dd2c0-43f8-499c-b8b6-0b6ce890abc0_1","type":"light","deviceType":"light","createdAt":"2022-12-19T07:16:11.000Z","isReachable":true,"lastSeen":"2024-08-23T07:58:07.000Z","attributes":{"isOn":true},"remoteLinks":["9371c9ac-3933-48fc-9bc5-adee7f1ac6ac_1"]}}
{"id":"cebae671-7468-4126-b298-4656d7602b44","time":"2024-08-23T07:58:07.000Z","specversion":"3.160.0","source":"urn:com:ikea:homesmart:iotc:zigbee","type":"deviceStateChanged","data":{"id":"663a9feb-9262-4f36-9194-f21c6f1260da_1","type":"light","deviceType":"light","createdAt":"2022-12-19T07:15:41.000Z","isReachable":true,"lastSeen":"2024-08-23T07:58:07.000Z","attributes":{"isOn":true},"remoteLinks":["9371c9ac-3933-48fc-9bc5-adee7f1ac6ac_1"]}}
{"id":"47b914b1-2e7b-4551-bdba-8828632e6368","time":"2024-08-23T07:58:07.000Z","specversion":"3.160.0","source":"urn:com:ikea:homesmart:iotc:zigbee","type":"deviceStateChanged","data":{"id":"2abb37e4-466f-4640-b574-fa3391fcf074_1","type":"light","deviceType":"light","createdAt":"2022-12-19T07:16:06.000Z","isReachable":true,"lastSeen":"2024-08-23T07:58:07.000Z","attributes":{"isOn":true},"remoteLinks":["9371c9ac-3933-48fc-9bc5-adee7f1ac6ac_1"]}}
{"id":"6b4fa3d4-4f73-4104-bd60-af8c8a29ffb3","time":"2024-08-23T07:58:08.000Z","specversion":"3.160.0","source":"urn:com:ikea:homesmart:iotc:zigbee","type":"deviceStateChanged","data":{"id":"a4e7d7d1-bdd7-4314-b5f2-4656f222300f_1","type":"light","deviceType":"light","createdAt":"2022-12-19T07:15:57.000Z","isReachable":true,"lastSeen":"2024-08-23T07:58:08.000Z","attributes":{"isOn":true},"remoteLinks":["9371c9ac-3933-48fc-9bc5-adee7f1ac6ac_1"]}}

**Third Log:**
This error originated from a custom integration.

Logger: custom_components.dirigera_platform
Source: custom_components/dirigera_platform/hub_event_listener.py:156
integration: IKEA Dirigera Hub Integration (documentation, issues)
First occurred: 5:02:37 PM (251 occurrences)
Last logged: 5:58:08 PM

'NoneType' object has no attribute 'loop'

**Comment by sanjoyg** [comment]
I had fixed this, are you using the latest release?

**Comment by sanjoyg** [comment]
Closing this as have not got any feedback
