### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by giannibuttarazzi** [sanjoyg/dirigera_platform#71]
hi guys sorry for such a basic question but I am unable to add the custom repository anyone could help me 
 Thank you 

![IMG_2512](https://github.com/user-attachments/assets/320cd4d9-19b6-4ddb-83a9-0b82a1fb8d94)

**Comment by srk8082** [comment]
Check the url and make sure it is full URL. eg: https://github.com/sanjoyg/dirigera_platform.git

**Comment by sanjoyg** [comment]
did it resolve?

**Comment by giannibuttarazzi** [comment]
Hey man ! Thank you for your reply ... apologies I didn't answer yet I will check later on and come back to you ...

**Comment by giannibuttarazzi** [comment]
@sanjoyg thank you !! Does work amazing !
