### ISSUE TITLE
v 1.8.2 - Dirigera battery sensors are unavailable.

### ISSUE THREAD

**Issue by bjo3rns** [sanjoyg/dirigera_platform#77]
IKEA Dirigera Hub Integration v 1.8.2

I noticed a mistake today: all Dirigera battery sensors are unavailable. The motion sensors are working.

![IMG_8132](https://github.com/user-attachments/assets/4cfcf62a-70d4-42c5-aabb-34b45874e058)

**Comment by bjo3rns** [comment]
`2024-10-09 12:27:02.634 ERROR (MainThread) [custom_components.dirigera_platform] Starting async_setup...
2024-10-09 12:27:02.635 ERROR (MainThread) [custom_components.dirigera_platform] config key: default_config value: {} `

**Comment by sanjoyg** [comment]
You would have to re install the integration. There was an earlier bug that caused the battery sensors to be added but it would not show the %. Now the correct battery sensors are added.

**Comment by sg26565** [comment]
Battery status is displayed again with v1.8.3 except for bulbs and outlets (which makes sense ;-))

![grafik](https://github.com/user-attachments/assets/3091e0e2-9ae3-46aa-bd95-df812e52ca36)

**Comment by sanjoyg** [comment]
Fixed now
