### ISSUE TITLE
INSPELNING causes Dirigera to stop responding in Original IKEA app and Home Assistant

### ISSUE THREAD

**Issue by TomasLudvik** [sanjoyg/dirigera_platform#86]
Thank you for your work on this plugin, it is greatly appreciated.

Yesterday I have added 10 INSPELNINGs to my Dirigera and then the IKEA app started to not respond. It was saying Hub is connected, right away disconnected and this kept happening forever. I was loooking for the problem and I found out, that disabling Dirigera integration plugin in my Home assistant stopped the issue. Before I was using this plugin for several weeks and I had no problem at all. Thats why I suspect INSPELNING intergration might somehow "overload" Dirigera and cause it to stop responding. Controls in Home Assistant were not working as well. What was working without flaws was my remotes and Homekit.

Used version of plugin: 1.8.8 . All other things like Home Controller are also fully updated.

**Comment by sanjoyg** [comment]
That is interesting, the integration doesnt really poll. Would you enable the plugin with debug on. Notice for any error messages and see if that is the issue. Also please try release 1.8.9 has a fix for INSPELLING

**Comment by Leave-MeAlone** [comment]
I also did have timeout messages in previous versions, will check tonight..

**Comment by sanjoyg** [comment]
Try 2.0 and do let me know

**Comment by sanjoyg** [comment]
Re-open if this still exists
