### ISSUE TITLE
Battery level worked in 1.8.4 but not in later versions

### ISSUE THREAD

**Issue by thstieler** [sanjoyg/dirigera_platform#89]
Prefaced I'm deeply grateful to your efforts to support the Ikea Dirigera platform in Home Assistant, and I think this integration`s approach is much more promising than waiting for Matter support.

But unfortunately I have a somehow mixed experience with the integration: I was co-reporter in issue #44.

With git tag 1.8.4 of the integration, I happily see the battery levels in the device overview:
![image](https://github.com/user-attachments/assets/4ab154aa-1046-44df-913d-d29ad0ba483b)

But after updating to 1.8.5 (and later version), I loose battery information, again.

The device list doesn't show the battery level for my devices anymore, by example for the motion sensor:
![image](https://github.com/user-attachments/assets/4f8939e8-84af-45c3-b0a5-4d71a1bdf6d6)

And when opening the device, the battery percentage is shown as not available:
![image](https://github.com/user-attachments/assets/02f4bd57-029c-454b-b0ec-b570c2209e5f)

Maybe this is relevant, with 1.8.4 I see an error message from dirigera_platform/scene.py: 
[1.8.4.txt](https://github.com/user-attachments/files/17386452/1.8.4.txt)

With 1.8.5 and later version, this error message occurs as well, but there is another error associated with the changed handling of empty scenes (introduced with [this commit]https://github.com/sanjoyg/dirigera_platform/commit/96db9af1f0c1663b1a90be81050ec8efc001f956):
[1.8.9.txt](https://github.com/user-attachments/files/17386544/1.8.9.txt)

**Comment by Leave-MeAlone** [comment]
for me with the latest version it's working ok.. I had the same issue as you had with earlier versions
![2024-10-16 11_32_12-Settings – Home Assistant and 5 more pages - Work - Microsoft​ Edge](https://github.com/user-attachments/assets/b19dc105-52de-4cdc-a216-e61bac946492)

**Comment by Leave-MeAlone** [comment]
> @Leave-MeAlone Which Dirigera integration and Home Assistant Core version do you use?
> 
> I'm running Docker image with version "Core 2024.10.2" and Dirigera integration checked out directly from git with tag 1.8.9., maybe there is an issue with this combination of versions?

Core
2024.10.2

Supervisor
2024.10.2

Operating System
13.2

Frontend
20241002.3

And Dirigera 1.8.9 

Have 2 the same systems running, as I'm building a clean instance both working the same

**Comment by thstieler** [comment]
Ah, that quite interesting: So it's really the scene handling that breaks things.

I will delete the only one scene I have (it's my christmas scene, still more than two month left for the fix ;-) ) and give it another try...

**Comment by thstieler** [comment]
Ok, I can confirm that without a scene the Initialisation works and the batteries (and other entities) are shown correctly.

**Comment by sanjoyg** [comment]
Looking into it...

**Comment by thstieler** [comment]
I briefly tried.

Wow, looks great: All entities seem to be available, even after creating the scene.

Christmas can come 🎅...
