### ISSUE TITLE
Dozens and dozens of empty scenes

### ISSUE THREAD

**Issue by MasseR** [sanjoyg/dirigera_platform#90]
I started getting a lot of empty scenes a while ago. I'm not sure what is causing this.

![image](https://github.com/user-attachments/assets/2fa455da-a8a0-4762-886f-303f4db07b33)

**Comment by sanjoyg** [comment]
Those are created as a hack to have the controller events been available
into hass automation

**Comment by sanjoyg** [comment]
Update to 2.0 should be gone
