### ISSUE TITLE
IKEA Inspelning lead to connection terminations

### ISSUE THREAD

**Issue by pischipinky** [sanjoyg/dirigera_platform#96]
Hello,

Please excuse my bad English.

As soon as I add the Inspelning socket, there are connection problems between HA and the dirigera hub

The original Ikea app then also gets connection problems.

If the INSPELNING are removed manually from HA or even the complete integration, the connection is available without problems.

Unfortunately, I don't get a JSON dump from the protocols.

I feel here what I could copy.
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.dirigera_platform
Quelle: custom_components/dirigera_platform/base_classes.py:92
Integration: IKEA Dirigera Hub Integration (Dokumentation, Probleme)
Erstmals aufgetreten: 19:30:10 (3776 Vorkommnisse)
Zuletzt protokolliert: 19:51:22

HTTPSConnectionPool(host='192.168.178.21', port=8443): Read timed out. (read timeout=10)

Logger: homeassistant.components.cover
Quelle: helpers/entity_platform.py:1020
Integration: Abdeckung (Dokumentation, Probleme)
Erstmals aufgetreten: 19:30:15 (91 Vorkommnisse)
Zuletzt protokolliert: 20:15:16

Updating dirigera_platform cover took longer than the scheduled update interval 0:00:15

**Comment by fa-ve** [comment]
I have also quite some some read time outs, already mentioned before....

**Comment by sanjoyg** [comment]
I am trying to fix this, can I please request you to do the following
1. Turn debug on
2. Send in generated hub_events (will be in the log) that are generated by switching on/off, changes in current consumption.

**Comment by Rednas79** [comment]
Got the same issue even with automations.

![image](https://github.com/user-attachments/assets/79a71b04-dbc7-4b13-b71d-386a67fc96a0)

Enabled debug mode will share the results later.

**Comment by sanjoyg** [comment]
Can you paste the exception from the log

**Comment by Rednas79** [comment]
[home-assistant_dirigera_platform_2024-10-30T15-43-16.317Z.log](https://github.com/user-attachments/files/17575520/home-assistant_dirigera_platform_2024-10-30T15-43-16.317Z.log)

Here the log.
Somehow it didn't work that wel.

But got an automation starting at 30m before sun rise, and it didn't run.
Started it manually like 2 a 3 min. later and it worked.

**Comment by sanjoyg** [comment]
Would you try the latest beta release 2.5.2. Polling of outlets have been taken out

**Comment by sanjoyg** [comment]
Try the latest release, these issues should not be there

**Comment by Rednas79** [comment]
sorry for the late responds but indeed no more issues
